string(REGEX REPLACE "^\"|\"$" "" SOURCE_SCRIPTS "${SOURCE_SCRIPTS}")
string(REGEX REPLACE "^\"|\"$" "" COMPILED_SCRIPTS "${COMPILED_SCRIPTS}")
string(REGEX REPLACE "^\"|\"$" "" OUTPUT_FOLDER "${OUTPUT_FOLDER}")

file(TO_CMAKE_PATH "${SOURCE_SCRIPTS}" SOURCE_SCRIPTS)
file(TO_CMAKE_PATH "${COMPILED_SCRIPTS}" COMPILED_SCRIPTS)
file(TO_CMAKE_PATH "${OUTPUT_FOLDER}" OUTPUT_FOLDER)

if(EXISTS "${SOURCE_SCRIPTS}")
    set(DEST_SRC "${OUTPUT_FOLDER}/Source/Scripts")
    message(STATUS "Copying Papyrus source scripts from ${SOURCE_SCRIPTS} to ${DEST_SRC}")
    file(REMOVE_RECURSE "${OUTPUT_FOLDER}/Source")
    file(MAKE_DIRECTORY "${DEST_SRC}")
    file(COPY "${SOURCE_SCRIPTS}/" DESTINATION "${DEST_SRC}")
else()
    message(STATUS "Papyrus source scripts not found at ${SOURCE_SCRIPTS}, skipping.")
endif()

if(EXISTS "${COMPILED_SCRIPTS}")
    set(DEST_COMPILED "${OUTPUT_FOLDER}/Scripts")
    message(STATUS "Copying compiled Papyrus scripts from ${COMPILED_SCRIPTS} to ${DEST_COMPILED}")
    file(REMOVE_RECURSE "${DEST_COMPILED}")
    file(MAKE_DIRECTORY "${DEST_COMPILED}")
    file(COPY "${COMPILED_SCRIPTS}/" DESTINATION "${DEST_COMPILED}")
else()
    message(STATUS "Compiled Papyrus scripts not found at ${COMPILED_SCRIPTS}, skipping.")
endif()
